# Generated by Django 2.2.3 on 2019-08-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Publication_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('Body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
